/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appHomeRouteRouteImport } from './routes/(app)/_home/route'
import { Route as appAuthRouteRouteImport } from './routes/(app)/_auth/route'
import { Route as appAppRouteRouteImport } from './routes/(app)/_app/route'
import { Route as appAdminRouteRouteImport } from './routes/(app)/_admin/route'
import { Route as appHomeIndexRouteImport } from './routes/(app)/_home/index'
import { Route as appAuthLoginRouteImport } from './routes/(app)/_auth/login'
import { Route as appAppActivateRouteImport } from './routes/(app)/_app/activate'
import { Route as appAppAccountRouteRouteImport } from './routes/(app)/_app/account/route'
import { Route as appHomeFeedIndexRouteImport } from './routes/(app)/_home/feed/index'
import { Route as appAppOverviewIndexRouteImport } from './routes/(app)/_app/overview/index'
import { Route as appAppCreatorIndexRouteImport } from './routes/(app)/_app/creator/index'
import { Route as appAppChatIndexRouteImport } from './routes/(app)/_app/chat/index'
import { Route as appHomeLegalsTermsRouteImport } from './routes/(app)/_home/legals/terms'
import { Route as appHomeLegalsPrivacyPolicyRouteImport } from './routes/(app)/_home/legals/privacy-policy'
import { Route as appHomeFeedSlugRouteImport } from './routes/(app)/_home/feed/$slug'
import { Route as appAppCreatorIdRouteImport } from './routes/(app)/_app/creator/$id'
import { Route as appAppStudioTopicsIndexRouteImport } from './routes/(app)/_app/studio/topics/index'
import { Route as appAppStudioSettingsIndexRouteImport } from './routes/(app)/_app/studio/settings/index'
import { Route as appAppStudioReviewIndexRouteImport } from './routes/(app)/_app/studio/review/index'
import { Route as appAppAccountSecurityIndexRouteImport } from './routes/(app)/_app/account/security/index'
import { Route as appAppAccountProfileIndexRouteImport } from './routes/(app)/_app/account/profile/index'
import { Route as appAppAccountBillingIndexRouteImport } from './routes/(app)/_app/account/billing/index'
import { Route as appAppAccountApiKeyIndexRouteImport } from './routes/(app)/_app/account/api-key/index'
import { Route as appAdminSUsersIndexRouteImport } from './routes/(app)/_admin/s/users/index'
import { Route as appAdminSOverviewIndexRouteImport } from './routes/(app)/_admin/s/overview/index'
import { Route as appAdminSEventsIndexRouteImport } from './routes/(app)/_admin/s/events/index'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appHomeRouteRoute = appHomeRouteRouteImport.update({
  id: '/_home',
  getParentRoute: () => appRouteRoute,
} as any)
const appAuthRouteRoute = appAuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => appRouteRoute,
} as any)
const appAppRouteRoute = appAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => appRouteRoute,
} as any)
const appAdminRouteRoute = appAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => appRouteRoute,
} as any)
const appHomeIndexRoute = appHomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appHomeRouteRoute,
} as any)
const appAuthLoginRoute = appAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => appAuthRouteRoute,
} as any)
const appAppActivateRoute = appAppActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => appAppRouteRoute,
} as any)
const appAppAccountRouteRoute = appAppAccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => appAppRouteRoute,
} as any)
const appHomeFeedIndexRoute = appHomeFeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => appHomeRouteRoute,
} as any)
const appAppOverviewIndexRoute = appAppOverviewIndexRouteImport.update({
  id: '/overview/',
  path: '/overview/',
  getParentRoute: () => appAppRouteRoute,
} as any)
const appAppCreatorIndexRoute = appAppCreatorIndexRouteImport.update({
  id: '/creator/',
  path: '/creator/',
  getParentRoute: () => appAppRouteRoute,
} as any)
const appAppChatIndexRoute = appAppChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => appAppRouteRoute,
} as any)
const appHomeLegalsTermsRoute = appHomeLegalsTermsRouteImport.update({
  id: '/legals/terms',
  path: '/legals/terms',
  getParentRoute: () => appHomeRouteRoute,
} as any)
const appHomeLegalsPrivacyPolicyRoute =
  appHomeLegalsPrivacyPolicyRouteImport.update({
    id: '/legals/privacy-policy',
    path: '/legals/privacy-policy',
    getParentRoute: () => appHomeRouteRoute,
  } as any)
const appHomeFeedSlugRoute = appHomeFeedSlugRouteImport.update({
  id: '/feed/$slug',
  path: '/feed/$slug',
  getParentRoute: () => appHomeRouteRoute,
} as any)
const appAppCreatorIdRoute = appAppCreatorIdRouteImport.update({
  id: '/creator/$id',
  path: '/creator/$id',
  getParentRoute: () => appAppRouteRoute,
} as any)
const appAppStudioTopicsIndexRoute = appAppStudioTopicsIndexRouteImport.update({
  id: '/studio/topics/',
  path: '/studio/topics/',
  getParentRoute: () => appAppRouteRoute,
} as any)
const appAppStudioSettingsIndexRoute =
  appAppStudioSettingsIndexRouteImport.update({
    id: '/studio/settings/',
    path: '/studio/settings/',
    getParentRoute: () => appAppRouteRoute,
  } as any)
const appAppStudioReviewIndexRoute = appAppStudioReviewIndexRouteImport.update({
  id: '/studio/review/',
  path: '/studio/review/',
  getParentRoute: () => appAppRouteRoute,
} as any)
const appAppAccountSecurityIndexRoute =
  appAppAccountSecurityIndexRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => appAppAccountRouteRoute,
  } as any)
const appAppAccountProfileIndexRoute =
  appAppAccountProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => appAppAccountRouteRoute,
  } as any)
const appAppAccountBillingIndexRoute =
  appAppAccountBillingIndexRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => appAppAccountRouteRoute,
  } as any)
const appAppAccountApiKeyIndexRoute =
  appAppAccountApiKeyIndexRouteImport.update({
    id: '/api-key/',
    path: '/api-key/',
    getParentRoute: () => appAppAccountRouteRoute,
  } as any)
const appAdminSUsersIndexRoute = appAdminSUsersIndexRouteImport.update({
  id: '/s/users/',
  path: '/s/users/',
  getParentRoute: () => appAdminRouteRoute,
} as any)
const appAdminSOverviewIndexRoute = appAdminSOverviewIndexRouteImport.update({
  id: '/s/overview/',
  path: '/s/overview/',
  getParentRoute: () => appAdminRouteRoute,
} as any)
const appAdminSEventsIndexRoute = appAdminSEventsIndexRouteImport.update({
  id: '/s/events/',
  path: '/s/events/',
  getParentRoute: () => appAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/account': typeof appAppAccountRouteRouteWithChildren
  '/activate': typeof appAppActivateRoute
  '/login': typeof appAuthLoginRoute
  '/': typeof appHomeIndexRoute
  '/creator/$id': typeof appAppCreatorIdRoute
  '/feed/$slug': typeof appHomeFeedSlugRoute
  '/legals/privacy-policy': typeof appHomeLegalsPrivacyPolicyRoute
  '/legals/terms': typeof appHomeLegalsTermsRoute
  '/chat/': typeof appAppChatIndexRoute
  '/creator/': typeof appAppCreatorIndexRoute
  '/overview/': typeof appAppOverviewIndexRoute
  '/feed/': typeof appHomeFeedIndexRoute
  '/s/events/': typeof appAdminSEventsIndexRoute
  '/s/overview/': typeof appAdminSOverviewIndexRoute
  '/s/users/': typeof appAdminSUsersIndexRoute
  '/account/api-key/': typeof appAppAccountApiKeyIndexRoute
  '/account/billing/': typeof appAppAccountBillingIndexRoute
  '/account/profile/': typeof appAppAccountProfileIndexRoute
  '/account/security/': typeof appAppAccountSecurityIndexRoute
  '/studio/review/': typeof appAppStudioReviewIndexRoute
  '/studio/settings/': typeof appAppStudioSettingsIndexRoute
  '/studio/topics/': typeof appAppStudioTopicsIndexRoute
}
export interface FileRoutesByTo {
  '/account': typeof appAppAccountRouteRouteWithChildren
  '/activate': typeof appAppActivateRoute
  '/login': typeof appAuthLoginRoute
  '/': typeof appHomeIndexRoute
  '/creator/$id': typeof appAppCreatorIdRoute
  '/feed/$slug': typeof appHomeFeedSlugRoute
  '/legals/privacy-policy': typeof appHomeLegalsPrivacyPolicyRoute
  '/legals/terms': typeof appHomeLegalsTermsRoute
  '/chat': typeof appAppChatIndexRoute
  '/creator': typeof appAppCreatorIndexRoute
  '/overview': typeof appAppOverviewIndexRoute
  '/feed': typeof appHomeFeedIndexRoute
  '/s/events': typeof appAdminSEventsIndexRoute
  '/s/overview': typeof appAdminSOverviewIndexRoute
  '/s/users': typeof appAdminSUsersIndexRoute
  '/account/api-key': typeof appAppAccountApiKeyIndexRoute
  '/account/billing': typeof appAppAccountBillingIndexRoute
  '/account/profile': typeof appAppAccountProfileIndexRoute
  '/account/security': typeof appAppAccountSecurityIndexRoute
  '/studio/review': typeof appAppStudioReviewIndexRoute
  '/studio/settings': typeof appAppStudioSettingsIndexRoute
  '/studio/topics': typeof appAppStudioTopicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/_admin': typeof appAdminRouteRouteWithChildren
  '/(app)/_app': typeof appAppRouteRouteWithChildren
  '/(app)/_auth': typeof appAuthRouteRouteWithChildren
  '/(app)/_home': typeof appHomeRouteRouteWithChildren
  '/(app)/_app/account': typeof appAppAccountRouteRouteWithChildren
  '/(app)/_app/activate': typeof appAppActivateRoute
  '/(app)/_auth/login': typeof appAuthLoginRoute
  '/(app)/_home/': typeof appHomeIndexRoute
  '/(app)/_app/creator/$id': typeof appAppCreatorIdRoute
  '/(app)/_home/feed/$slug': typeof appHomeFeedSlugRoute
  '/(app)/_home/legals/privacy-policy': typeof appHomeLegalsPrivacyPolicyRoute
  '/(app)/_home/legals/terms': typeof appHomeLegalsTermsRoute
  '/(app)/_app/chat/': typeof appAppChatIndexRoute
  '/(app)/_app/creator/': typeof appAppCreatorIndexRoute
  '/(app)/_app/overview/': typeof appAppOverviewIndexRoute
  '/(app)/_home/feed/': typeof appHomeFeedIndexRoute
  '/(app)/_admin/s/events/': typeof appAdminSEventsIndexRoute
  '/(app)/_admin/s/overview/': typeof appAdminSOverviewIndexRoute
  '/(app)/_admin/s/users/': typeof appAdminSUsersIndexRoute
  '/(app)/_app/account/api-key/': typeof appAppAccountApiKeyIndexRoute
  '/(app)/_app/account/billing/': typeof appAppAccountBillingIndexRoute
  '/(app)/_app/account/profile/': typeof appAppAccountProfileIndexRoute
  '/(app)/_app/account/security/': typeof appAppAccountSecurityIndexRoute
  '/(app)/_app/studio/review/': typeof appAppStudioReviewIndexRoute
  '/(app)/_app/studio/settings/': typeof appAppStudioSettingsIndexRoute
  '/(app)/_app/studio/topics/': typeof appAppStudioTopicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/account'
    | '/activate'
    | '/login'
    | '/'
    | '/creator/$id'
    | '/feed/$slug'
    | '/legals/privacy-policy'
    | '/legals/terms'
    | '/chat/'
    | '/creator/'
    | '/overview/'
    | '/feed/'
    | '/s/events/'
    | '/s/overview/'
    | '/s/users/'
    | '/account/api-key/'
    | '/account/billing/'
    | '/account/profile/'
    | '/account/security/'
    | '/studio/review/'
    | '/studio/settings/'
    | '/studio/topics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account'
    | '/activate'
    | '/login'
    | '/'
    | '/creator/$id'
    | '/feed/$slug'
    | '/legals/privacy-policy'
    | '/legals/terms'
    | '/chat'
    | '/creator'
    | '/overview'
    | '/feed'
    | '/s/events'
    | '/s/overview'
    | '/s/users'
    | '/account/api-key'
    | '/account/billing'
    | '/account/profile'
    | '/account/security'
    | '/studio/review'
    | '/studio/settings'
    | '/studio/topics'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/_admin'
    | '/(app)/_app'
    | '/(app)/_auth'
    | '/(app)/_home'
    | '/(app)/_app/account'
    | '/(app)/_app/activate'
    | '/(app)/_auth/login'
    | '/(app)/_home/'
    | '/(app)/_app/creator/$id'
    | '/(app)/_home/feed/$slug'
    | '/(app)/_home/legals/privacy-policy'
    | '/(app)/_home/legals/terms'
    | '/(app)/_app/chat/'
    | '/(app)/_app/creator/'
    | '/(app)/_app/overview/'
    | '/(app)/_home/feed/'
    | '/(app)/_admin/s/events/'
    | '/(app)/_admin/s/overview/'
    | '/(app)/_admin/s/users/'
    | '/(app)/_app/account/api-key/'
    | '/(app)/_app/account/billing/'
    | '/(app)/_app/account/profile/'
    | '/(app)/_app/account/security/'
    | '/(app)/_app/studio/review/'
    | '/(app)/_app/studio/settings/'
    | '/(app)/_app/studio/topics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_home': {
      id: '/(app)/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appHomeRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/_auth': {
      id: '/(app)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appAuthRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/_app': {
      id: '/(app)/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appAppRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/_admin': {
      id: '/(app)/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appAdminRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/_home/': {
      id: '/(app)/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appHomeIndexRouteImport
      parentRoute: typeof appHomeRouteRoute
    }
    '/(app)/_auth/login': {
      id: '/(app)/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof appAuthLoginRouteImport
      parentRoute: typeof appAuthRouteRoute
    }
    '/(app)/_app/activate': {
      id: '/(app)/_app/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof appAppActivateRouteImport
      parentRoute: typeof appAppRouteRoute
    }
    '/(app)/_app/account': {
      id: '/(app)/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof appAppAccountRouteRouteImport
      parentRoute: typeof appAppRouteRoute
    }
    '/(app)/_home/feed/': {
      id: '/(app)/_home/feed/'
      path: '/feed'
      fullPath: '/feed/'
      preLoaderRoute: typeof appHomeFeedIndexRouteImport
      parentRoute: typeof appHomeRouteRoute
    }
    '/(app)/_app/overview/': {
      id: '/(app)/_app/overview/'
      path: '/overview'
      fullPath: '/overview/'
      preLoaderRoute: typeof appAppOverviewIndexRouteImport
      parentRoute: typeof appAppRouteRoute
    }
    '/(app)/_app/creator/': {
      id: '/(app)/_app/creator/'
      path: '/creator'
      fullPath: '/creator/'
      preLoaderRoute: typeof appAppCreatorIndexRouteImport
      parentRoute: typeof appAppRouteRoute
    }
    '/(app)/_app/chat/': {
      id: '/(app)/_app/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof appAppChatIndexRouteImport
      parentRoute: typeof appAppRouteRoute
    }
    '/(app)/_home/legals/terms': {
      id: '/(app)/_home/legals/terms'
      path: '/legals/terms'
      fullPath: '/legals/terms'
      preLoaderRoute: typeof appHomeLegalsTermsRouteImport
      parentRoute: typeof appHomeRouteRoute
    }
    '/(app)/_home/legals/privacy-policy': {
      id: '/(app)/_home/legals/privacy-policy'
      path: '/legals/privacy-policy'
      fullPath: '/legals/privacy-policy'
      preLoaderRoute: typeof appHomeLegalsPrivacyPolicyRouteImport
      parentRoute: typeof appHomeRouteRoute
    }
    '/(app)/_home/feed/$slug': {
      id: '/(app)/_home/feed/$slug'
      path: '/feed/$slug'
      fullPath: '/feed/$slug'
      preLoaderRoute: typeof appHomeFeedSlugRouteImport
      parentRoute: typeof appHomeRouteRoute
    }
    '/(app)/_app/creator/$id': {
      id: '/(app)/_app/creator/$id'
      path: '/creator/$id'
      fullPath: '/creator/$id'
      preLoaderRoute: typeof appAppCreatorIdRouteImport
      parentRoute: typeof appAppRouteRoute
    }
    '/(app)/_app/studio/topics/': {
      id: '/(app)/_app/studio/topics/'
      path: '/studio/topics'
      fullPath: '/studio/topics/'
      preLoaderRoute: typeof appAppStudioTopicsIndexRouteImport
      parentRoute: typeof appAppRouteRoute
    }
    '/(app)/_app/studio/settings/': {
      id: '/(app)/_app/studio/settings/'
      path: '/studio/settings'
      fullPath: '/studio/settings/'
      preLoaderRoute: typeof appAppStudioSettingsIndexRouteImport
      parentRoute: typeof appAppRouteRoute
    }
    '/(app)/_app/studio/review/': {
      id: '/(app)/_app/studio/review/'
      path: '/studio/review'
      fullPath: '/studio/review/'
      preLoaderRoute: typeof appAppStudioReviewIndexRouteImport
      parentRoute: typeof appAppRouteRoute
    }
    '/(app)/_app/account/security/': {
      id: '/(app)/_app/account/security/'
      path: '/security'
      fullPath: '/account/security/'
      preLoaderRoute: typeof appAppAccountSecurityIndexRouteImport
      parentRoute: typeof appAppAccountRouteRoute
    }
    '/(app)/_app/account/profile/': {
      id: '/(app)/_app/account/profile/'
      path: '/profile'
      fullPath: '/account/profile/'
      preLoaderRoute: typeof appAppAccountProfileIndexRouteImport
      parentRoute: typeof appAppAccountRouteRoute
    }
    '/(app)/_app/account/billing/': {
      id: '/(app)/_app/account/billing/'
      path: '/billing'
      fullPath: '/account/billing/'
      preLoaderRoute: typeof appAppAccountBillingIndexRouteImport
      parentRoute: typeof appAppAccountRouteRoute
    }
    '/(app)/_app/account/api-key/': {
      id: '/(app)/_app/account/api-key/'
      path: '/api-key'
      fullPath: '/account/api-key/'
      preLoaderRoute: typeof appAppAccountApiKeyIndexRouteImport
      parentRoute: typeof appAppAccountRouteRoute
    }
    '/(app)/_admin/s/users/': {
      id: '/(app)/_admin/s/users/'
      path: '/s/users'
      fullPath: '/s/users/'
      preLoaderRoute: typeof appAdminSUsersIndexRouteImport
      parentRoute: typeof appAdminRouteRoute
    }
    '/(app)/_admin/s/overview/': {
      id: '/(app)/_admin/s/overview/'
      path: '/s/overview'
      fullPath: '/s/overview/'
      preLoaderRoute: typeof appAdminSOverviewIndexRouteImport
      parentRoute: typeof appAdminRouteRoute
    }
    '/(app)/_admin/s/events/': {
      id: '/(app)/_admin/s/events/'
      path: '/s/events'
      fullPath: '/s/events/'
      preLoaderRoute: typeof appAdminSEventsIndexRouteImport
      parentRoute: typeof appAdminRouteRoute
    }
  }
}

interface appAdminRouteRouteChildren {
  appAdminSEventsIndexRoute: typeof appAdminSEventsIndexRoute
  appAdminSOverviewIndexRoute: typeof appAdminSOverviewIndexRoute
  appAdminSUsersIndexRoute: typeof appAdminSUsersIndexRoute
}

const appAdminRouteRouteChildren: appAdminRouteRouteChildren = {
  appAdminSEventsIndexRoute: appAdminSEventsIndexRoute,
  appAdminSOverviewIndexRoute: appAdminSOverviewIndexRoute,
  appAdminSUsersIndexRoute: appAdminSUsersIndexRoute,
}

const appAdminRouteRouteWithChildren = appAdminRouteRoute._addFileChildren(
  appAdminRouteRouteChildren,
)

interface appAppAccountRouteRouteChildren {
  appAppAccountApiKeyIndexRoute: typeof appAppAccountApiKeyIndexRoute
  appAppAccountBillingIndexRoute: typeof appAppAccountBillingIndexRoute
  appAppAccountProfileIndexRoute: typeof appAppAccountProfileIndexRoute
  appAppAccountSecurityIndexRoute: typeof appAppAccountSecurityIndexRoute
}

const appAppAccountRouteRouteChildren: appAppAccountRouteRouteChildren = {
  appAppAccountApiKeyIndexRoute: appAppAccountApiKeyIndexRoute,
  appAppAccountBillingIndexRoute: appAppAccountBillingIndexRoute,
  appAppAccountProfileIndexRoute: appAppAccountProfileIndexRoute,
  appAppAccountSecurityIndexRoute: appAppAccountSecurityIndexRoute,
}

const appAppAccountRouteRouteWithChildren =
  appAppAccountRouteRoute._addFileChildren(appAppAccountRouteRouteChildren)

interface appAppRouteRouteChildren {
  appAppAccountRouteRoute: typeof appAppAccountRouteRouteWithChildren
  appAppActivateRoute: typeof appAppActivateRoute
  appAppCreatorIdRoute: typeof appAppCreatorIdRoute
  appAppChatIndexRoute: typeof appAppChatIndexRoute
  appAppCreatorIndexRoute: typeof appAppCreatorIndexRoute
  appAppOverviewIndexRoute: typeof appAppOverviewIndexRoute
  appAppStudioReviewIndexRoute: typeof appAppStudioReviewIndexRoute
  appAppStudioSettingsIndexRoute: typeof appAppStudioSettingsIndexRoute
  appAppStudioTopicsIndexRoute: typeof appAppStudioTopicsIndexRoute
}

const appAppRouteRouteChildren: appAppRouteRouteChildren = {
  appAppAccountRouteRoute: appAppAccountRouteRouteWithChildren,
  appAppActivateRoute: appAppActivateRoute,
  appAppCreatorIdRoute: appAppCreatorIdRoute,
  appAppChatIndexRoute: appAppChatIndexRoute,
  appAppCreatorIndexRoute: appAppCreatorIndexRoute,
  appAppOverviewIndexRoute: appAppOverviewIndexRoute,
  appAppStudioReviewIndexRoute: appAppStudioReviewIndexRoute,
  appAppStudioSettingsIndexRoute: appAppStudioSettingsIndexRoute,
  appAppStudioTopicsIndexRoute: appAppStudioTopicsIndexRoute,
}

const appAppRouteRouteWithChildren = appAppRouteRoute._addFileChildren(
  appAppRouteRouteChildren,
)

interface appAuthRouteRouteChildren {
  appAuthLoginRoute: typeof appAuthLoginRoute
}

const appAuthRouteRouteChildren: appAuthRouteRouteChildren = {
  appAuthLoginRoute: appAuthLoginRoute,
}

const appAuthRouteRouteWithChildren = appAuthRouteRoute._addFileChildren(
  appAuthRouteRouteChildren,
)

interface appHomeRouteRouteChildren {
  appHomeIndexRoute: typeof appHomeIndexRoute
  appHomeFeedSlugRoute: typeof appHomeFeedSlugRoute
  appHomeLegalsPrivacyPolicyRoute: typeof appHomeLegalsPrivacyPolicyRoute
  appHomeLegalsTermsRoute: typeof appHomeLegalsTermsRoute
  appHomeFeedIndexRoute: typeof appHomeFeedIndexRoute
}

const appHomeRouteRouteChildren: appHomeRouteRouteChildren = {
  appHomeIndexRoute: appHomeIndexRoute,
  appHomeFeedSlugRoute: appHomeFeedSlugRoute,
  appHomeLegalsPrivacyPolicyRoute: appHomeLegalsPrivacyPolicyRoute,
  appHomeLegalsTermsRoute: appHomeLegalsTermsRoute,
  appHomeFeedIndexRoute: appHomeFeedIndexRoute,
}

const appHomeRouteRouteWithChildren = appHomeRouteRoute._addFileChildren(
  appHomeRouteRouteChildren,
)

interface appRouteRouteChildren {
  appAdminRouteRoute: typeof appAdminRouteRouteWithChildren
  appAppRouteRoute: typeof appAppRouteRouteWithChildren
  appAuthRouteRoute: typeof appAuthRouteRouteWithChildren
  appHomeRouteRoute: typeof appHomeRouteRouteWithChildren
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAdminRouteRoute: appAdminRouteRouteWithChildren,
  appAppRouteRoute: appAppRouteRouteWithChildren,
  appAuthRouteRoute: appAuthRouteRouteWithChildren,
  appHomeRouteRoute: appHomeRouteRouteWithChildren,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
